### ISSUE TITLE
Unclear on using in an external site

### ISSUE THREAD

**Issue by jareko999** [ElMassimo/vue-custom-element-example#1]
Hey @ElMassimo,

Can I use your dark mode switch on my site? How would I do that? I tried this:

```
<script type="module" src="https://raw.githubusercontent.com/ElMassimo/vue-custom-element-example/main/package/src/index.ts"></script>
```

But it did not work. 

Basically, I'm trying to build a "widget" that someone can embed on their site (like your dark mode switch), but am unclear how you would embed a Vue custom element on an external site. So, how would I embed your dark mode switch on my site? Is that possible?

**Comment by ElMassimo** [comment]
Hi @jareko999!

If you would like to build a widget, see the [_Packaging as a Library_ section of the blog post](https://maximomussini.com/posts/vue-custom-elements#packaging-as-a-library).

I've [published](https://github.com/ElMassimo/vue-custom-element-example/blob/main/package/package.json) this example in npm as `@mussi/vue-custom-element-example`.

You can see it [being included here](https://github.com/ElMassimo/vue-custom-element-example/blob/main/playground/main.ts#L3-L5), to get [this example working](https://github.com/ElMassimo/vue-custom-element-example/blob/main/playground/index.html#L18).

**Comment by jareko999** [comment]
Great, thanks!

**Comment by Shashirokz** [comment]
Hey @ElMassimo,

I cloned the project, did npm install and run the project. I'm getting error.. attached the photo. 

![Error](https://user-images.githubusercontent.com/7167560/181241097-686c8ca6-02d5-4f79-80fe-7337546def6f.PNG)

Can you help?

**Comment by ElMassimo** [comment]
Just checked and I can't replicate that error.

Make sure to run `pnpm install` in the `package` and `playground` dirs, and to build the `package` first before running `dev` in the `playground` dir.

I've updated the example to use Vite 3 and the latest Vue, feel free to pull from this repo and try again.
