### ISSUE TITLE
Including vue-router and pinia

### ISSUE THREAD

**Issue by mrcego** [ElMassimo/vue-custom-element-example#2]
Hey @ElMassimo, thanks for this invaluable repo, I was able to build and ship a complex Web Component with Chart.JS and Tailwind, pretty cool and I enjoyed a lot, your repo was very helpful.

I want to go step ahead with this approach and I wanna know if you have thought about how to include `vue-router` and `pinia` libraries, so we might using them without any issue. I'm trying implement [this approach](https://stackoverflow.com/a/73019181/19044212) but I have been finding some caveats. I will be thankfully if you help me putting this in the right direction with this.

Regards!

**Comment by onurusluca** [comment]
@mrcego Hey! I am also using that solution. What kind of caveats have you been facing? My projects works fine with some fine tuning. Maybe I can help.

**Comment by mrcego** [comment]
> @mrcego Hey! I am also using that solution. What kind of caveats have you been facing? My projects works fine with some fine tuning. Maybe I can help.

Hey @onurusluca. Could you mind sharing an example about how do you made it works? I'm interested and I know I'm missing something to do full functional but my lack of knowledge is an issue 🤣. Thanks in advanced.

**Comment by onurusluca** [comment]
I didn't have much problems. It was working as it was. I just did some refactoring. 
Our cases are probably very different. If you have any problems, mention here. Maybe I help.

**Comment by mrcego** [comment]
> I didn't have much problems. It was working as it was. I just did some refactoring. 
> Our cases are probably very different. If you have any problems, mention here. Maybe I help.
> 

How did you handling styles thing? I mean, just creating `styles` prop?

**Comment by mrcego** [comment]
OK, I was able to make it works! I want to know how to type correctly that approach. Any hints about `getCurrentInstances()`, `styles` and `component`types? I was searching at `vue-runtime-dom` definition without success. Thanks in advanced.

**Comment by Hellrasier** [comment]
@onurusluca Do your emits work for web-components, when you use that solution? Because I found out, that you can't emit an event, if you wrap your defineCustomElement for adding plugins
