### ISSUE TITLE
Can we publish on NPM and using in React/Next ?

### ISSUE THREAD

**Issue by vhalegax** [ElMassimo/vue-custom-element-example#3]
Wanna ask, can we publish on NPM and using in React/Next ? thankyou

**Comment by ElMassimo** [comment]
Hi Wisnu, I'm not sure I understand the question.

Are you suggesting that I publish this example in `npm`, and that you would like to use it in a React project?

**Comment by vhalegax** [comment]
Hi, sorry i am asking wrong question
